//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region Métadonnées de relation EDM

[assembly: EdmRelationshipAttribute("GSB_Equipe4", "FK_RAPPORT_VISITE_COLLABORATEUR", "COLLABORATEUR", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Swiss_visite.COLLABORATEUR), "RAPPORT_VISITE", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Swiss_visite.RAPPORT_VISITE), true)]
[assembly: EdmRelationshipAttribute("GSB_Equipe4", "FK_OFFRIR_MEDICAMENT", "MEDICAMENT", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Swiss_visite.MEDICAMENT), "OFFRIR", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Swiss_visite.OFFRIR), true)]
[assembly: EdmRelationshipAttribute("GSB_Equipe4", "FK_RAPPORT_VISITE_MOTIF", "MOTIF", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Swiss_visite.MOTIF), "RAPPORT_VISITE", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Swiss_visite.RAPPORT_VISITE), true)]
[assembly: EdmRelationshipAttribute("GSB_Equipe4", "FK_OFFRIR_RAPPORT_VISITE", "RAPPORT_VISITE", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Swiss_visite.RAPPORT_VISITE), "OFFRIR", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Swiss_visite.OFFRIR), true)]
[assembly: EdmRelationshipAttribute("GSB_Equipe4", "FK_RAPPORT_VISITE_PRATICIEN", "PRATICIEN", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Swiss_visite.PRATICIEN), "RAPPORT_VISITE", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Swiss_visite.RAPPORT_VISITE), true)]

#endregion

namespace Swiss_visite
{
    #region Contextes
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    public partial class ConnectDBGSB : ObjectContext
    {
        #region Constructeurs
    
        /// <summary>
        /// Initialise un nouvel objet ConnectDBGSB à l'aide de la chaîne de connexion trouvée dans la section 'ConnectDBGSB' du fichier de configuration d'application.
        /// </summary>
        public ConnectDBGSB() : base("name=ConnectDBGSB", "ConnectDBGSB")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisez un nouvel objet ConnectDBGSB.
        /// </summary>
        public ConnectDBGSB(string connectionString) : base(connectionString, "ConnectDBGSB")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisez un nouvel objet ConnectDBGSB.
        /// </summary>
        public ConnectDBGSB(EntityConnection connection) : base(connection, "ConnectDBGSB")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Méthodes partielles
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propriétés ObjectSet
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<COLLABORATEUR> COLLABORATEURs
        {
            get
            {
                if ((_COLLABORATEURs == null))
                {
                    _COLLABORATEURs = base.CreateObjectSet<COLLABORATEUR>("COLLABORATEURs");
                }
                return _COLLABORATEURs;
            }
        }
        private ObjectSet<COLLABORATEUR> _COLLABORATEURs;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<MEDICAMENT> MEDICAMENTs
        {
            get
            {
                if ((_MEDICAMENTs == null))
                {
                    _MEDICAMENTs = base.CreateObjectSet<MEDICAMENT>("MEDICAMENTs");
                }
                return _MEDICAMENTs;
            }
        }
        private ObjectSet<MEDICAMENT> _MEDICAMENTs;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<MOTIF> MOTIFs
        {
            get
            {
                if ((_MOTIFs == null))
                {
                    _MOTIFs = base.CreateObjectSet<MOTIF>("MOTIFs");
                }
                return _MOTIFs;
            }
        }
        private ObjectSet<MOTIF> _MOTIFs;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<OFFRIR> OFFRIRs
        {
            get
            {
                if ((_OFFRIRs == null))
                {
                    _OFFRIRs = base.CreateObjectSet<OFFRIR>("OFFRIRs");
                }
                return _OFFRIRs;
            }
        }
        private ObjectSet<OFFRIR> _OFFRIRs;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<PRATICIEN> PRATICIENs
        {
            get
            {
                if ((_PRATICIENs == null))
                {
                    _PRATICIENs = base.CreateObjectSet<PRATICIEN>("PRATICIENs");
                }
                return _PRATICIENs;
            }
        }
        private ObjectSet<PRATICIEN> _PRATICIENs;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<RAPPORT_VISITE> RAPPORT_VISITE
        {
            get
            {
                if ((_RAPPORT_VISITE == null))
                {
                    _RAPPORT_VISITE = base.CreateObjectSet<RAPPORT_VISITE>("RAPPORT_VISITE");
                }
                return _RAPPORT_VISITE;
            }
        }
        private ObjectSet<RAPPORT_VISITE> _RAPPORT_VISITE;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<SWITCHBOARD_ITEMS> SWITCHBOARD_ITEMS
        {
            get
            {
                if ((_SWITCHBOARD_ITEMS == null))
                {
                    _SWITCHBOARD_ITEMS = base.CreateObjectSet<SWITCHBOARD_ITEMS>("SWITCHBOARD_ITEMS");
                }
                return _SWITCHBOARD_ITEMS;
            }
        }
        private ObjectSet<SWITCHBOARD_ITEMS> _SWITCHBOARD_ITEMS;

        #endregion
        #region Méthodes AddTo
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet COLLABORATEURs. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToCOLLABORATEURs(COLLABORATEUR cOLLABORATEUR)
        {
            base.AddObject("COLLABORATEURs", cOLLABORATEUR);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet MEDICAMENTs. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToMEDICAMENTs(MEDICAMENT mEDICAMENT)
        {
            base.AddObject("MEDICAMENTs", mEDICAMENT);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet MOTIFs. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToMOTIFs(MOTIF mOTIF)
        {
            base.AddObject("MOTIFs", mOTIF);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet OFFRIRs. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToOFFRIRs(OFFRIR oFFRIR)
        {
            base.AddObject("OFFRIRs", oFFRIR);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet PRATICIENs. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToPRATICIENs(PRATICIEN pRATICIEN)
        {
            base.AddObject("PRATICIENs", pRATICIEN);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet RAPPORT_VISITE. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToRAPPORT_VISITE(RAPPORT_VISITE rAPPORT_VISITE)
        {
            base.AddObject("RAPPORT_VISITE", rAPPORT_VISITE);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet SWITCHBOARD_ITEMS. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToSWITCHBOARD_ITEMS(SWITCHBOARD_ITEMS sWITCHBOARD_ITEMS)
        {
            base.AddObject("SWITCHBOARD_ITEMS", sWITCHBOARD_ITEMS);
        }

        #endregion
    }
    

    #endregion
    
    #region Entités
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GSB_Equipe4", Name="COLLABORATEUR")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class COLLABORATEUR : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet COLLABORATEUR.
        /// </summary>
        /// <param name="cOL_MATRICULE">Valeur initiale de la propriété COL_MATRICULE.</param>
        public static COLLABORATEUR CreateCOLLABORATEUR(global::System.String cOL_MATRICULE)
        {
            COLLABORATEUR cOLLABORATEUR = new COLLABORATEUR();
            cOLLABORATEUR.COL_MATRICULE = cOL_MATRICULE;
            return cOLLABORATEUR;
        }

        #endregion
        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String COL_MATRICULE
        {
            get
            {
                return _COL_MATRICULE;
            }
            set
            {
                if (_COL_MATRICULE != value)
                {
                    OnCOL_MATRICULEChanging(value);
                    ReportPropertyChanging("COL_MATRICULE");
                    _COL_MATRICULE = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("COL_MATRICULE");
                    OnCOL_MATRICULEChanged();
                }
            }
        }
        private global::System.String _COL_MATRICULE;
        partial void OnCOL_MATRICULEChanging(global::System.String value);
        partial void OnCOL_MATRICULEChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String COL_NOM
        {
            get
            {
                return _COL_NOM;
            }
            set
            {
                OnCOL_NOMChanging(value);
                ReportPropertyChanging("COL_NOM");
                _COL_NOM = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("COL_NOM");
                OnCOL_NOMChanged();
            }
        }
        private global::System.String _COL_NOM;
        partial void OnCOL_NOMChanging(global::System.String value);
        partial void OnCOL_NOMChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String COL_PRENOM
        {
            get
            {
                return _COL_PRENOM;
            }
            set
            {
                OnCOL_PRENOMChanging(value);
                ReportPropertyChanging("COL_PRENOM");
                _COL_PRENOM = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("COL_PRENOM");
                OnCOL_PRENOMChanged();
            }
        }
        private global::System.String _COL_PRENOM;
        partial void OnCOL_PRENOMChanging(global::System.String value);
        partial void OnCOL_PRENOMChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String COL_ADRESSE
        {
            get
            {
                return _COL_ADRESSE;
            }
            set
            {
                OnCOL_ADRESSEChanging(value);
                ReportPropertyChanging("COL_ADRESSE");
                _COL_ADRESSE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("COL_ADRESSE");
                OnCOL_ADRESSEChanged();
            }
        }
        private global::System.String _COL_ADRESSE;
        partial void OnCOL_ADRESSEChanging(global::System.String value);
        partial void OnCOL_ADRESSEChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String COL_CP
        {
            get
            {
                return _COL_CP;
            }
            set
            {
                OnCOL_CPChanging(value);
                ReportPropertyChanging("COL_CP");
                _COL_CP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("COL_CP");
                OnCOL_CPChanged();
            }
        }
        private global::System.String _COL_CP;
        partial void OnCOL_CPChanging(global::System.String value);
        partial void OnCOL_CPChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String COL_VILLE
        {
            get
            {
                return _COL_VILLE;
            }
            set
            {
                OnCOL_VILLEChanging(value);
                ReportPropertyChanging("COL_VILLE");
                _COL_VILLE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("COL_VILLE");
                OnCOL_VILLEChanged();
            }
        }
        private global::System.String _COL_VILLE;
        partial void OnCOL_VILLEChanging(global::System.String value);
        partial void OnCOL_VILLEChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String COL_DATEEMBAUCHE
        {
            get
            {
                return _COL_DATEEMBAUCHE;
            }
            set
            {
                OnCOL_DATEEMBAUCHEChanging(value);
                ReportPropertyChanging("COL_DATEEMBAUCHE");
                _COL_DATEEMBAUCHE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("COL_DATEEMBAUCHE");
                OnCOL_DATEEMBAUCHEChanged();
            }
        }
        private global::System.String _COL_DATEEMBAUCHE;
        partial void OnCOL_DATEEMBAUCHEChanging(global::System.String value);
        partial void OnCOL_DATEEMBAUCHEChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String COL_NIVEAU_ACCES
        {
            get
            {
                return _COL_NIVEAU_ACCES;
            }
            set
            {
                OnCOL_NIVEAU_ACCESChanging(value);
                ReportPropertyChanging("COL_NIVEAU_ACCES");
                _COL_NIVEAU_ACCES = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("COL_NIVEAU_ACCES");
                OnCOL_NIVEAU_ACCESChanged();
            }
        }
        private global::System.String _COL_NIVEAU_ACCES;
        partial void OnCOL_NIVEAU_ACCESChanging(global::System.String value);
        partial void OnCOL_NIVEAU_ACCESChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String COL_MDP
        {
            get
            {
                return _COL_MDP;
            }
            set
            {
                OnCOL_MDPChanging(value);
                ReportPropertyChanging("COL_MDP");
                _COL_MDP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("COL_MDP");
                OnCOL_MDPChanged();
            }
        }
        private global::System.String _COL_MDP;
        partial void OnCOL_MDPChanging(global::System.String value);
        partial void OnCOL_MDPChanged();

        #endregion
    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GSB_Equipe4", "FK_RAPPORT_VISITE_COLLABORATEUR", "RAPPORT_VISITE")]
        public EntityCollection<RAPPORT_VISITE> RAPPORT_VISITE
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<RAPPORT_VISITE>("GSB_Equipe4.FK_RAPPORT_VISITE_COLLABORATEUR", "RAPPORT_VISITE");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<RAPPORT_VISITE>("GSB_Equipe4.FK_RAPPORT_VISITE_COLLABORATEUR", "RAPPORT_VISITE", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GSB_Equipe4", Name="MEDICAMENT")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MEDICAMENT : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet MEDICAMENT.
        /// </summary>
        /// <param name="mED_DEPOTLEGAL">Valeur initiale de la propriété MED_DEPOTLEGAL.</param>
        public static MEDICAMENT CreateMEDICAMENT(global::System.String mED_DEPOTLEGAL)
        {
            MEDICAMENT mEDICAMENT = new MEDICAMENT();
            mEDICAMENT.MED_DEPOTLEGAL = mED_DEPOTLEGAL;
            return mEDICAMENT;
        }

        #endregion
        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MED_DEPOTLEGAL
        {
            get
            {
                return _MED_DEPOTLEGAL;
            }
            set
            {
                if (_MED_DEPOTLEGAL != value)
                {
                    OnMED_DEPOTLEGALChanging(value);
                    ReportPropertyChanging("MED_DEPOTLEGAL");
                    _MED_DEPOTLEGAL = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("MED_DEPOTLEGAL");
                    OnMED_DEPOTLEGALChanged();
                }
            }
        }
        private global::System.String _MED_DEPOTLEGAL;
        partial void OnMED_DEPOTLEGALChanging(global::System.String value);
        partial void OnMED_DEPOTLEGALChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MED_NOMCOMMERCIAL
        {
            get
            {
                return _MED_NOMCOMMERCIAL;
            }
            set
            {
                OnMED_NOMCOMMERCIALChanging(value);
                ReportPropertyChanging("MED_NOMCOMMERCIAL");
                _MED_NOMCOMMERCIAL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MED_NOMCOMMERCIAL");
                OnMED_NOMCOMMERCIALChanged();
            }
        }
        private global::System.String _MED_NOMCOMMERCIAL;
        partial void OnMED_NOMCOMMERCIALChanging(global::System.String value);
        partial void OnMED_NOMCOMMERCIALChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MED_COMPOSITION
        {
            get
            {
                return _MED_COMPOSITION;
            }
            set
            {
                OnMED_COMPOSITIONChanging(value);
                ReportPropertyChanging("MED_COMPOSITION");
                _MED_COMPOSITION = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MED_COMPOSITION");
                OnMED_COMPOSITIONChanged();
            }
        }
        private global::System.String _MED_COMPOSITION;
        partial void OnMED_COMPOSITIONChanging(global::System.String value);
        partial void OnMED_COMPOSITIONChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MED_EFFETS
        {
            get
            {
                return _MED_EFFETS;
            }
            set
            {
                OnMED_EFFETSChanging(value);
                ReportPropertyChanging("MED_EFFETS");
                _MED_EFFETS = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MED_EFFETS");
                OnMED_EFFETSChanged();
            }
        }
        private global::System.String _MED_EFFETS;
        partial void OnMED_EFFETSChanging(global::System.String value);
        partial void OnMED_EFFETSChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MED_CONTREINDIC
        {
            get
            {
                return _MED_CONTREINDIC;
            }
            set
            {
                OnMED_CONTREINDICChanging(value);
                ReportPropertyChanging("MED_CONTREINDIC");
                _MED_CONTREINDIC = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MED_CONTREINDIC");
                OnMED_CONTREINDICChanged();
            }
        }
        private global::System.String _MED_CONTREINDIC;
        partial void OnMED_CONTREINDICChanging(global::System.String value);
        partial void OnMED_CONTREINDICChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MED_PRIXECHANTILLON
        {
            get
            {
                return _MED_PRIXECHANTILLON;
            }
            set
            {
                OnMED_PRIXECHANTILLONChanging(value);
                ReportPropertyChanging("MED_PRIXECHANTILLON");
                _MED_PRIXECHANTILLON = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MED_PRIXECHANTILLON");
                OnMED_PRIXECHANTILLONChanged();
            }
        }
        private Nullable<global::System.Int32> _MED_PRIXECHANTILLON;
        partial void OnMED_PRIXECHANTILLONChanging(Nullable<global::System.Int32> value);
        partial void OnMED_PRIXECHANTILLONChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MED_DATESORTIE
        {
            get
            {
                return _MED_DATESORTIE;
            }
            set
            {
                OnMED_DATESORTIEChanging(value);
                ReportPropertyChanging("MED_DATESORTIE");
                _MED_DATESORTIE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MED_DATESORTIE");
                OnMED_DATESORTIEChanged();
            }
        }
        private global::System.String _MED_DATESORTIE;
        partial void OnMED_DATESORTIEChanging(global::System.String value);
        partial void OnMED_DATESORTIEChanged();

        #endregion
    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GSB_Equipe4", "FK_OFFRIR_MEDICAMENT", "OFFRIR")]
        public EntityCollection<OFFRIR> OFFRIRs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<OFFRIR>("GSB_Equipe4.FK_OFFRIR_MEDICAMENT", "OFFRIR");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<OFFRIR>("GSB_Equipe4.FK_OFFRIR_MEDICAMENT", "OFFRIR", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GSB_Equipe4", Name="MOTIF")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MOTIF : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet MOTIF.
        /// </summary>
        /// <param name="mOT_NUM">Valeur initiale de la propriété MOT_NUM.</param>
        public static MOTIF CreateMOTIF(global::System.String mOT_NUM)
        {
            MOTIF mOTIF = new MOTIF();
            mOTIF.MOT_NUM = mOT_NUM;
            return mOTIF;
        }

        #endregion
        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MOT_NUM
        {
            get
            {
                return _MOT_NUM;
            }
            set
            {
                if (_MOT_NUM != value)
                {
                    OnMOT_NUMChanging(value);
                    ReportPropertyChanging("MOT_NUM");
                    _MOT_NUM = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("MOT_NUM");
                    OnMOT_NUMChanged();
                }
            }
        }
        private global::System.String _MOT_NUM;
        partial void OnMOT_NUMChanging(global::System.String value);
        partial void OnMOT_NUMChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MOT_LIBELLE
        {
            get
            {
                return _MOT_LIBELLE;
            }
            set
            {
                OnMOT_LIBELLEChanging(value);
                ReportPropertyChanging("MOT_LIBELLE");
                _MOT_LIBELLE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MOT_LIBELLE");
                OnMOT_LIBELLEChanged();
            }
        }
        private global::System.String _MOT_LIBELLE;
        partial void OnMOT_LIBELLEChanging(global::System.String value);
        partial void OnMOT_LIBELLEChanged();

        #endregion
    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GSB_Equipe4", "FK_RAPPORT_VISITE_MOTIF", "RAPPORT_VISITE")]
        public EntityCollection<RAPPORT_VISITE> RAPPORT_VISITE
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<RAPPORT_VISITE>("GSB_Equipe4.FK_RAPPORT_VISITE_MOTIF", "RAPPORT_VISITE");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<RAPPORT_VISITE>("GSB_Equipe4.FK_RAPPORT_VISITE_MOTIF", "RAPPORT_VISITE", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GSB_Equipe4", Name="OFFRIR")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class OFFRIR : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet OFFRIR.
        /// </summary>
        /// <param name="mED_DEPOTLEGAL">Valeur initiale de la propriété MED_DEPOTLEGAL.</param>
        /// <param name="cOL_MATRICULE">Valeur initiale de la propriété COL_MATRICULE.</param>
        /// <param name="rAP_NUM">Valeur initiale de la propriété RAP_NUM.</param>
        public static OFFRIR CreateOFFRIR(global::System.String mED_DEPOTLEGAL, global::System.String cOL_MATRICULE, global::System.Int64 rAP_NUM)
        {
            OFFRIR oFFRIR = new OFFRIR();
            oFFRIR.MED_DEPOTLEGAL = mED_DEPOTLEGAL;
            oFFRIR.COL_MATRICULE = cOL_MATRICULE;
            oFFRIR.RAP_NUM = rAP_NUM;
            return oFFRIR;
        }

        #endregion
        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MED_DEPOTLEGAL
        {
            get
            {
                return _MED_DEPOTLEGAL;
            }
            set
            {
                if (_MED_DEPOTLEGAL != value)
                {
                    OnMED_DEPOTLEGALChanging(value);
                    ReportPropertyChanging("MED_DEPOTLEGAL");
                    _MED_DEPOTLEGAL = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("MED_DEPOTLEGAL");
                    OnMED_DEPOTLEGALChanged();
                }
            }
        }
        private global::System.String _MED_DEPOTLEGAL;
        partial void OnMED_DEPOTLEGALChanging(global::System.String value);
        partial void OnMED_DEPOTLEGALChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String COL_MATRICULE
        {
            get
            {
                return _COL_MATRICULE;
            }
            set
            {
                if (_COL_MATRICULE != value)
                {
                    OnCOL_MATRICULEChanging(value);
                    ReportPropertyChanging("COL_MATRICULE");
                    _COL_MATRICULE = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("COL_MATRICULE");
                    OnCOL_MATRICULEChanged();
                }
            }
        }
        private global::System.String _COL_MATRICULE;
        partial void OnCOL_MATRICULEChanging(global::System.String value);
        partial void OnCOL_MATRICULEChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 RAP_NUM
        {
            get
            {
                return _RAP_NUM;
            }
            set
            {
                if (_RAP_NUM != value)
                {
                    OnRAP_NUMChanging(value);
                    ReportPropertyChanging("RAP_NUM");
                    _RAP_NUM = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RAP_NUM");
                    OnRAP_NUMChanged();
                }
            }
        }
        private global::System.Int64 _RAP_NUM;
        partial void OnRAP_NUMChanging(global::System.Int64 value);
        partial void OnRAP_NUMChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String QTE_OFFERTE
        {
            get
            {
                return _QTE_OFFERTE;
            }
            set
            {
                OnQTE_OFFERTEChanging(value);
                ReportPropertyChanging("QTE_OFFERTE");
                _QTE_OFFERTE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("QTE_OFFERTE");
                OnQTE_OFFERTEChanged();
            }
        }
        private global::System.String _QTE_OFFERTE;
        partial void OnQTE_OFFERTEChanging(global::System.String value);
        partial void OnQTE_OFFERTEChanged();

        #endregion
    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GSB_Equipe4", "FK_OFFRIR_MEDICAMENT", "MEDICAMENT")]
        public MEDICAMENT MEDICAMENT
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MEDICAMENT>("GSB_Equipe4.FK_OFFRIR_MEDICAMENT", "MEDICAMENT").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MEDICAMENT>("GSB_Equipe4.FK_OFFRIR_MEDICAMENT", "MEDICAMENT").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<MEDICAMENT> MEDICAMENTReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MEDICAMENT>("GSB_Equipe4.FK_OFFRIR_MEDICAMENT", "MEDICAMENT");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<MEDICAMENT>("GSB_Equipe4.FK_OFFRIR_MEDICAMENT", "MEDICAMENT", value);
                }
            }
        }
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GSB_Equipe4", "FK_OFFRIR_RAPPORT_VISITE", "RAPPORT_VISITE")]
        public RAPPORT_VISITE RAPPORT_VISITE
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RAPPORT_VISITE>("GSB_Equipe4.FK_OFFRIR_RAPPORT_VISITE", "RAPPORT_VISITE").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RAPPORT_VISITE>("GSB_Equipe4.FK_OFFRIR_RAPPORT_VISITE", "RAPPORT_VISITE").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<RAPPORT_VISITE> RAPPORT_VISITEReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RAPPORT_VISITE>("GSB_Equipe4.FK_OFFRIR_RAPPORT_VISITE", "RAPPORT_VISITE");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<RAPPORT_VISITE>("GSB_Equipe4.FK_OFFRIR_RAPPORT_VISITE", "RAPPORT_VISITE", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GSB_Equipe4", Name="PRATICIEN")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PRATICIEN : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet PRATICIEN.
        /// </summary>
        /// <param name="pRA_NUM">Valeur initiale de la propriété PRA_NUM.</param>
        public static PRATICIEN CreatePRATICIEN(global::System.Int32 pRA_NUM)
        {
            PRATICIEN pRATICIEN = new PRATICIEN();
            pRATICIEN.PRA_NUM = pRA_NUM;
            return pRATICIEN;
        }

        #endregion
        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PRA_NUM
        {
            get
            {
                return _PRA_NUM;
            }
            set
            {
                if (_PRA_NUM != value)
                {
                    OnPRA_NUMChanging(value);
                    ReportPropertyChanging("PRA_NUM");
                    _PRA_NUM = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PRA_NUM");
                    OnPRA_NUMChanged();
                }
            }
        }
        private global::System.Int32 _PRA_NUM;
        partial void OnPRA_NUMChanging(global::System.Int32 value);
        partial void OnPRA_NUMChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PRA_NOM
        {
            get
            {
                return _PRA_NOM;
            }
            set
            {
                OnPRA_NOMChanging(value);
                ReportPropertyChanging("PRA_NOM");
                _PRA_NOM = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PRA_NOM");
                OnPRA_NOMChanged();
            }
        }
        private global::System.String _PRA_NOM;
        partial void OnPRA_NOMChanging(global::System.String value);
        partial void OnPRA_NOMChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PRA_PRENOM
        {
            get
            {
                return _PRA_PRENOM;
            }
            set
            {
                OnPRA_PRENOMChanging(value);
                ReportPropertyChanging("PRA_PRENOM");
                _PRA_PRENOM = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PRA_PRENOM");
                OnPRA_PRENOMChanged();
            }
        }
        private global::System.String _PRA_PRENOM;
        partial void OnPRA_PRENOMChanging(global::System.String value);
        partial void OnPRA_PRENOMChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PRA_ADRESSE
        {
            get
            {
                return _PRA_ADRESSE;
            }
            set
            {
                OnPRA_ADRESSEChanging(value);
                ReportPropertyChanging("PRA_ADRESSE");
                _PRA_ADRESSE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PRA_ADRESSE");
                OnPRA_ADRESSEChanged();
            }
        }
        private global::System.String _PRA_ADRESSE;
        partial void OnPRA_ADRESSEChanging(global::System.String value);
        partial void OnPRA_ADRESSEChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PRA_CP
        {
            get
            {
                return _PRA_CP;
            }
            set
            {
                OnPRA_CPChanging(value);
                ReportPropertyChanging("PRA_CP");
                _PRA_CP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PRA_CP");
                OnPRA_CPChanged();
            }
        }
        private global::System.String _PRA_CP;
        partial void OnPRA_CPChanging(global::System.String value);
        partial void OnPRA_CPChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PRA_VILLE
        {
            get
            {
                return _PRA_VILLE;
            }
            set
            {
                OnPRA_VILLEChanging(value);
                ReportPropertyChanging("PRA_VILLE");
                _PRA_VILLE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PRA_VILLE");
                OnPRA_VILLEChanged();
            }
        }
        private global::System.String _PRA_VILLE;
        partial void OnPRA_VILLEChanging(global::System.String value);
        partial void OnPRA_VILLEChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> PRA_COEFNOTORIETE
        {
            get
            {
                return _PRA_COEFNOTORIETE;
            }
            set
            {
                OnPRA_COEFNOTORIETEChanging(value);
                ReportPropertyChanging("PRA_COEFNOTORIETE");
                _PRA_COEFNOTORIETE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PRA_COEFNOTORIETE");
                OnPRA_COEFNOTORIETEChanged();
            }
        }
        private Nullable<global::System.Single> _PRA_COEFNOTORIETE;
        partial void OnPRA_COEFNOTORIETEChanging(Nullable<global::System.Single> value);
        partial void OnPRA_COEFNOTORIETEChanged();

        #endregion
    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GSB_Equipe4", "FK_RAPPORT_VISITE_PRATICIEN", "RAPPORT_VISITE")]
        public EntityCollection<RAPPORT_VISITE> RAPPORT_VISITE
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<RAPPORT_VISITE>("GSB_Equipe4.FK_RAPPORT_VISITE_PRATICIEN", "RAPPORT_VISITE");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<RAPPORT_VISITE>("GSB_Equipe4.FK_RAPPORT_VISITE_PRATICIEN", "RAPPORT_VISITE", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GSB_Equipe4", Name="RAPPORT_VISITE")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class RAPPORT_VISITE : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet RAPPORT_VISITE.
        /// </summary>
        /// <param name="cOL_MATRICULE">Valeur initiale de la propriété COL_MATRICULE.</param>
        /// <param name="rAP_NUM">Valeur initiale de la propriété RAP_NUM.</param>
        /// <param name="mOT_NUM">Valeur initiale de la propriété MOT_NUM.</param>
        /// <param name="pRA_NUM">Valeur initiale de la propriété PRA_NUM.</param>
        public static RAPPORT_VISITE CreateRAPPORT_VISITE(global::System.String cOL_MATRICULE, global::System.Int64 rAP_NUM, global::System.String mOT_NUM, global::System.Int32 pRA_NUM)
        {
            RAPPORT_VISITE rAPPORT_VISITE = new RAPPORT_VISITE();
            rAPPORT_VISITE.COL_MATRICULE = cOL_MATRICULE;
            rAPPORT_VISITE.RAP_NUM = rAP_NUM;
            rAPPORT_VISITE.MOT_NUM = mOT_NUM;
            rAPPORT_VISITE.PRA_NUM = pRA_NUM;
            return rAPPORT_VISITE;
        }

        #endregion
        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String COL_MATRICULE
        {
            get
            {
                return _COL_MATRICULE;
            }
            set
            {
                if (_COL_MATRICULE != value)
                {
                    OnCOL_MATRICULEChanging(value);
                    ReportPropertyChanging("COL_MATRICULE");
                    _COL_MATRICULE = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("COL_MATRICULE");
                    OnCOL_MATRICULEChanged();
                }
            }
        }
        private global::System.String _COL_MATRICULE;
        partial void OnCOL_MATRICULEChanging(global::System.String value);
        partial void OnCOL_MATRICULEChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 RAP_NUM
        {
            get
            {
                return _RAP_NUM;
            }
            set
            {
                if (_RAP_NUM != value)
                {
                    OnRAP_NUMChanging(value);
                    ReportPropertyChanging("RAP_NUM");
                    _RAP_NUM = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RAP_NUM");
                    OnRAP_NUMChanged();
                }
            }
        }
        private global::System.Int64 _RAP_NUM;
        partial void OnRAP_NUMChanging(global::System.Int64 value);
        partial void OnRAP_NUMChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MOT_NUM
        {
            get
            {
                return _MOT_NUM;
            }
            set
            {
                OnMOT_NUMChanging(value);
                ReportPropertyChanging("MOT_NUM");
                _MOT_NUM = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MOT_NUM");
                OnMOT_NUMChanged();
            }
        }
        private global::System.String _MOT_NUM;
        partial void OnMOT_NUMChanging(global::System.String value);
        partial void OnMOT_NUMChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PRA_NUM
        {
            get
            {
                return _PRA_NUM;
            }
            set
            {
                OnPRA_NUMChanging(value);
                ReportPropertyChanging("PRA_NUM");
                _PRA_NUM = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PRA_NUM");
                OnPRA_NUMChanged();
            }
        }
        private global::System.Int32 _PRA_NUM;
        partial void OnPRA_NUMChanging(global::System.Int32 value);
        partial void OnPRA_NUMChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> RAP_DATE
        {
            get
            {
                return _RAP_DATE;
            }
            set
            {
                OnRAP_DATEChanging(value);
                ReportPropertyChanging("RAP_DATE");
                _RAP_DATE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RAP_DATE");
                OnRAP_DATEChanged();
            }
        }
        private Nullable<global::System.DateTime> _RAP_DATE;
        partial void OnRAP_DATEChanging(Nullable<global::System.DateTime> value);
        partial void OnRAP_DATEChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RAP_BILAN
        {
            get
            {
                return _RAP_BILAN;
            }
            set
            {
                OnRAP_BILANChanging(value);
                ReportPropertyChanging("RAP_BILAN");
                _RAP_BILAN = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RAP_BILAN");
                OnRAP_BILANChanged();
            }
        }
        private global::System.String _RAP_BILAN;
        partial void OnRAP_BILANChanging(global::System.String value);
        partial void OnRAP_BILANChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RAP_DATE_SAISIE
        {
            get
            {
                return _RAP_DATE_SAISIE;
            }
            set
            {
                OnRAP_DATE_SAISIEChanging(value);
                ReportPropertyChanging("RAP_DATE_SAISIE");
                _RAP_DATE_SAISIE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RAP_DATE_SAISIE");
                OnRAP_DATE_SAISIEChanged();
            }
        }
        private global::System.String _RAP_DATE_SAISIE;
        partial void OnRAP_DATE_SAISIEChanging(global::System.String value);
        partial void OnRAP_DATE_SAISIEChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RAP_COEFFCONFIANCE
        {
            get
            {
                return _RAP_COEFFCONFIANCE;
            }
            set
            {
                OnRAP_COEFFCONFIANCEChanging(value);
                ReportPropertyChanging("RAP_COEFFCONFIANCE");
                _RAP_COEFFCONFIANCE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RAP_COEFFCONFIANCE");
                OnRAP_COEFFCONFIANCEChanged();
            }
        }
        private global::System.String _RAP_COEFFCONFIANCE;
        partial void OnRAP_COEFFCONFIANCEChanging(global::System.String value);
        partial void OnRAP_COEFFCONFIANCEChanged();

        #endregion
    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GSB_Equipe4", "FK_RAPPORT_VISITE_COLLABORATEUR", "COLLABORATEUR")]
        public COLLABORATEUR COLLABORATEUR
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<COLLABORATEUR>("GSB_Equipe4.FK_RAPPORT_VISITE_COLLABORATEUR", "COLLABORATEUR").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<COLLABORATEUR>("GSB_Equipe4.FK_RAPPORT_VISITE_COLLABORATEUR", "COLLABORATEUR").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<COLLABORATEUR> COLLABORATEURReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<COLLABORATEUR>("GSB_Equipe4.FK_RAPPORT_VISITE_COLLABORATEUR", "COLLABORATEUR");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<COLLABORATEUR>("GSB_Equipe4.FK_RAPPORT_VISITE_COLLABORATEUR", "COLLABORATEUR", value);
                }
            }
        }
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GSB_Equipe4", "FK_RAPPORT_VISITE_MOTIF", "MOTIF")]
        public MOTIF MOTIF
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MOTIF>("GSB_Equipe4.FK_RAPPORT_VISITE_MOTIF", "MOTIF").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MOTIF>("GSB_Equipe4.FK_RAPPORT_VISITE_MOTIF", "MOTIF").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<MOTIF> MOTIFReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MOTIF>("GSB_Equipe4.FK_RAPPORT_VISITE_MOTIF", "MOTIF");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<MOTIF>("GSB_Equipe4.FK_RAPPORT_VISITE_MOTIF", "MOTIF", value);
                }
            }
        }
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GSB_Equipe4", "FK_OFFRIR_RAPPORT_VISITE", "OFFRIR")]
        public EntityCollection<OFFRIR> OFFRIRs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<OFFRIR>("GSB_Equipe4.FK_OFFRIR_RAPPORT_VISITE", "OFFRIR");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<OFFRIR>("GSB_Equipe4.FK_OFFRIR_RAPPORT_VISITE", "OFFRIR", value);
                }
            }
        }
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GSB_Equipe4", "FK_RAPPORT_VISITE_PRATICIEN", "PRATICIEN")]
        public PRATICIEN PRATICIEN
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PRATICIEN>("GSB_Equipe4.FK_RAPPORT_VISITE_PRATICIEN", "PRATICIEN").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PRATICIEN>("GSB_Equipe4.FK_RAPPORT_VISITE_PRATICIEN", "PRATICIEN").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<PRATICIEN> PRATICIENReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PRATICIEN>("GSB_Equipe4.FK_RAPPORT_VISITE_PRATICIEN", "PRATICIEN");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<PRATICIEN>("GSB_Equipe4.FK_RAPPORT_VISITE_PRATICIEN", "PRATICIEN", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GSB_Equipe4", Name="SWITCHBOARD_ITEMS")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SWITCHBOARD_ITEMS : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet SWITCHBOARD_ITEMS.
        /// </summary>
        /// <param name="sWITCHBOARDID">Valeur initiale de la propriété SWITCHBOARDID.</param>
        /// <param name="iTEMNUMBER">Valeur initiale de la propriété ITEMNUMBER.</param>
        public static SWITCHBOARD_ITEMS CreateSWITCHBOARD_ITEMS(global::System.Int64 sWITCHBOARDID, global::System.Int32 iTEMNUMBER)
        {
            SWITCHBOARD_ITEMS sWITCHBOARD_ITEMS = new SWITCHBOARD_ITEMS();
            sWITCHBOARD_ITEMS.SWITCHBOARDID = sWITCHBOARDID;
            sWITCHBOARD_ITEMS.ITEMNUMBER = iTEMNUMBER;
            return sWITCHBOARD_ITEMS;
        }

        #endregion
        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 SWITCHBOARDID
        {
            get
            {
                return _SWITCHBOARDID;
            }
            set
            {
                if (_SWITCHBOARDID != value)
                {
                    OnSWITCHBOARDIDChanging(value);
                    ReportPropertyChanging("SWITCHBOARDID");
                    _SWITCHBOARDID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("SWITCHBOARDID");
                    OnSWITCHBOARDIDChanged();
                }
            }
        }
        private global::System.Int64 _SWITCHBOARDID;
        partial void OnSWITCHBOARDIDChanging(global::System.Int64 value);
        partial void OnSWITCHBOARDIDChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ITEMNUMBER
        {
            get
            {
                return _ITEMNUMBER;
            }
            set
            {
                if (_ITEMNUMBER != value)
                {
                    OnITEMNUMBERChanging(value);
                    ReportPropertyChanging("ITEMNUMBER");
                    _ITEMNUMBER = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ITEMNUMBER");
                    OnITEMNUMBERChanged();
                }
            }
        }
        private global::System.Int32 _ITEMNUMBER;
        partial void OnITEMNUMBERChanging(global::System.Int32 value);
        partial void OnITEMNUMBERChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ITEMTEXT
        {
            get
            {
                return _ITEMTEXT;
            }
            set
            {
                OnITEMTEXTChanging(value);
                ReportPropertyChanging("ITEMTEXT");
                _ITEMTEXT = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ITEMTEXT");
                OnITEMTEXTChanged();
            }
        }
        private global::System.String _ITEMTEXT;
        partial void OnITEMTEXTChanging(global::System.String value);
        partial void OnITEMTEXTChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> COMMAND
        {
            get
            {
                return _COMMAND;
            }
            set
            {
                OnCOMMANDChanging(value);
                ReportPropertyChanging("COMMAND");
                _COMMAND = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("COMMAND");
                OnCOMMANDChanged();
            }
        }
        private Nullable<global::System.Int32> _COMMAND;
        partial void OnCOMMANDChanging(Nullable<global::System.Int32> value);
        partial void OnCOMMANDChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ARGUMENT
        {
            get
            {
                return _ARGUMENT;
            }
            set
            {
                OnARGUMENTChanging(value);
                ReportPropertyChanging("ARGUMENT");
                _ARGUMENT = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ARGUMENT");
                OnARGUMENTChanged();
            }
        }
        private global::System.String _ARGUMENT;
        partial void OnARGUMENTChanging(global::System.String value);
        partial void OnARGUMENTChanged();

        #endregion
    
    }

    #endregion
    
}
